### ISSUE TITLE
Add to langserver.org

### ISSUE THREAD

**Issue by srenatus** [vladdu/vscode-erlang-lsp#1]
Hi there! I'm very excited about an Erlang language server. 👍 Thanks for doing this.

It'd be nice if this was added to the [langserver.org](http://langserver.org/) collection of LSP implementations. I'd do the PR, but I'm unsure about the currently supported features (see the website for the list).

Cheers
Stephan

**Comment by vladdu** [comment]
Hi and thanks! 

This is still very early, I only have a server that returns empty results. 

I am also considering to put the implementation together with one of the other Erlang plugins, so that I don't have to care about syntax highlighting and compiling/debugging and such, while users only have to install one extension. That will probably be https://github.com/pgourlain/vscode_erlang, that seems the most complete.

**Comment by srenatus** [comment]
Thanks for the feedback.

I see. I'll leave it up to you to keep this issue open for eventual addition to langserver.org -- feel free to close this 😉

**Comment by vladdu** [comment]
added sourcer, which is the language server proper
